# Generated by Django 4.2.6 on 2023-10-29 01:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='univeristycampus',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
